import ClassificationTemplate from "../model/expedient/classificationTemplate";

export async function seedDefaultClassificationTemplate() {
  const code = "default_hr_dossier";

  const commonDocs = [
    "application/pdf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ];

  const data = {
    code,
    name: "Expediente RRHH (Default)",
    version: 1,
    isActive: true,
    isDeleted: false,
    sections: [
      {
        key: "personalDocs",
        title: "1. Documentos Personales",
        order: 1,
        phase: "RECRUITMENT",
        items: [
          {
            key: "idCopy",
            label: "Copia de cédula o pasaporte",
            order: 1,
            required: true,
            multiple: false,
            accepts: [...commonDocs, "image/*"],
          },
          {
            key: "birthCertificate",
            label: "Acta de nacimiento",
            order: 2,
            required: false,
            multiple: false,
            accepts: commonDocs,
          },
          {
            key: "photoID",
            label: "Foto tipo carnet",
            order: 3,
            required: false,
            multiple: false,
            accepts: ["image/*"],
          },
          {
            key: "addressProof",
            label: "Comprobante de dirección",
            order: 4,
            required: false,
            multiple: false,
            accepts: commonDocs,
          },
        ],
      },
      {
        key: "legalContracts",
        title: "2. Documentos Legales y Contractuales",
        order: 2,
        phase: "EMPLOYEE",
        items: [
          {
            key: "workContract",
            label: "Contrato de trabajo",
            order: 1,
            required: true,
            multiple: false,
            accepts: commonDocs,
          },
          {
            key: "nda",
            label: "Acuerdos de confidencialidad",
            order: 2,
            required: false,
            multiple: false,
            accepts: commonDocs,
          },
          {
            key: "addendums",
            label: "Addendums o modificaciones al contrato",
            order: 3,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "internalPolicies",
            label: "Politicas internas",
            order: 4,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
        ],
      },
      {
        key: "recruiting",
        title: "3. Reclutamiento y Selección",
        order: 3,
        phase: "RECRUITMENT",
        items: [
          {
            key: "applicationForm",
            label: "Formulario de solicitud",
            order: 1,
            required: true,
            multiple: false,
            accepts: commonDocs,
          },
          {
            key: "cv",
            label: "Currículum vitae",
            order: 2,
            required: true,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "interviewResults",
            label: "Resultados de entrevistas",
            order: 3,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "psychTests",
            label: "Pruebas psicométricas y técnicas",
            order: 4,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
        ],
      },
      {
        key: "educationCerts",
        title: "4. Certificaciones y Educación",
        order: 4,
        phase: "RECRUITMENT",
        items: [
          {
            key: "degrees",
            label: "Títulos y diplomas",
            order: 1,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "professionalCerts",
            label: "Certificaciones profesionales",
            order: 2,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "trainings",
            label: "Cursos y entrenamientos completados",
            order: 3,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
        ],
      },
      {
        key: "attendance",
        title: "5. Control de Asistencia",
        order: 5,
        phase: "EMPLOYEE",
        items: [
          {
            key: "punchRecords",
            label: "Registros de ponches",
            order: 1,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "attendanceReports",
            label: "Reportes de asistencia",
            order: 2,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "overtime",
            label: "Horas extras",
            order: 3,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "shifts",
            label: "Turnos y horarios asignados",
            order: 4,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
        ],
      },
      {
        key: "performance",
        title: "6. Evaluación y Desempeño",
        order: 6,
        phase: "EMPLOYEE",
        items: [
          {
            key: "performanceReviews",
            label: "Evaluaciones de desempeño",
            order: 1,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "kpis",
            label: "Objetivos y KPIs",
            order: 2,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "improvementPlans",
            label: "Planes de mejora",
            order: 3,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
        ],
      },
      {
        key: "discipline",
        title: "7. Disciplina y Conducta",
        order: 7,
        phase: "EMPLOYEE",
        items: [
          {
            key: "warnings",
            label: "Amonestaciones",
            order: 1,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "incidents",
            label: "Incidentes",
            order: 2,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "disciplinaryMeasures",
            label: "Registros de medidas disciplinarias",
            order: 3,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
        ],
      },
      {
        key: "payrollBenefits",
        title: "8. Nómina y Beneficios",
        order: 8,
        phase: "EMPLOYEE",
        items: [
          {
            key: "payslips",
            label: "Talones de pago",
            order: 1,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "withholdings",
            label: "Retenciones e impuestos",
            order: 2,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "vacations",
            label: "Registros de vacaciones y licencias",
            order: 3,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "benefitsInsurance",
            label: "Beneficios y seguros",
            order: 4,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
        ],
      },
      {
        key: "healthSafety",
        title: "9. Salud, Seguridad y Bienestar",
        order: 9,
        phase: "EMPLOYEE",
        items: [
          {
            key: "medicalCerts",
            label: "Certificados médicos",
            order: 1,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "accidentReports",
            label: "Reportes de accidentes laborales",
            order: 2,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "occupationalHealth",
            label: "Evaluaciones de salud ocupacional",
            order: 3,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
        ],
      },
      {
        key: "separation",
        title: "10. Separación de la Empresa",
        order: 10,
        phase: "TERMINATION",
        items: [
          {
            key: "resignationLetter",
            label: "Carta de renuncia o despido",
            order: 1,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "settlement",
            label: "Liquidación",
            order: 2,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "exitInterview",
            label: "Entrevista de salida",
            order: 3,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
          {
            key: "equipmentChecklist",
            label: "Checklist de entrega de equipos",
            order: 4,
            required: false,
            multiple: true,
            accepts: commonDocs,
          },
        ],
      },
    ],
  };

  const doc = await ClassificationTemplate.findOneAndUpdate(
    { code, isDeleted: false }, 
    { $set: data }, 
    { upsert: true, new: true } 
  );

  return doc;
}
